ALTER TABLE tb_login
ADD login_nick VARCHAR2(50);

ALTER TABLE tb_login
DROP COLUMN login_nick;

ALTER TABLE tb_login
RENAME COLUMN login_name TO login_nick;

ALTER TRIGGER MP_24K_BIGDATA24_P2_3.TB_PET_AI_TRG COMPILE;

DROP TRIGGER MP_24K_BIGDATA24_P2_3.TB_PET_AI_TRG;

delete from tb_care;
delete from tb_pet;

DROP TRIGGER TB_PET_AI_TRG;
DROP SEQUENCE tb_pet_SEQ; 

CREATE SEQUENCE tb_pet_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER tb_pet_AI_TRG
BEFORE INSERT ON tb_pet 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT tb_pet_SEQ.NEXTVAL
    INTO :NEW.pet_idx
    FROM DUAL;
END;